[package]
name = "cd_audio"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "LGPL-2.1"
repository = "https://github.com/ChaosTheChaotic/cd_audio"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]

[build-dependencies]
cmake = "0.1.54"
pkg-config = "0.3.32"
