[package]
name = "cd_audio"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]

[build-dependencies]
cmake = "0.1.54"
pkg-config = "0.3.32"
